endpoints:
  sensitive: false
  actuator:
    enabled: true
management:
  security:
      enabled: false
info:
  app:
    java:
      source: 1.8
      target: 1.8
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

---
spring:
  profile: adjective
words: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
  profile: article
words: a,the

---
spring:
  profile: noun
words: boat,book,vote,seat,backpack,partition,groundhog

---
spring:
  profile: subject
words: I,You,He,She,It

---
spring:
  profile: verb
words: ran,knew,had,saw,bought