endpoints:
  sensitive: false
  actuator:
    enabled: true
management:
  security:
      enabled: false
info:
  app:
    java:
      source: 1.8
      target: 1.8
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

words: reasonable,leaky,suspicious,ordinary,unlikely